document.getElementsByClassName("color")[0].style.backgroundColor = "black"
document.getElementsByClassName("color")[0].innerHTML = "Black"
document.getElementsByClassName("color")[1].style.backgroundColor = "red"
document.getElementsByClassName("color")[1].innerHTML = "Red"
document.getElementsByClassName("color")[2].style.backgroundColor = "blue"
document.getElementsByClassName("color")[2].innerHTML = "Blue"
document.getElementsByClassName("color")[3].style.backgroundColor = "orange"
document.getElementsByClassName("color")[3].innerHTML = "Orange"
